// src/components/input/Input.tsx
import { Tooltip } from "@mui/material";
import { observer } from "mobx-react";
import React, { Component } from "react";
import styles from "./InputList.module.css";
import { parse } from "mathjs";

type Props = {
  /** The text to show before the number */
  title: string;
  /** The text to show before the number */
  suffix: string;
  /** Whether the input should be editable, or else italic and grayed out */
  enabled: boolean;
  /** The value of the input */
  number: number;
  /** The number of decimal places to show when not editing. */
  roundingPrecision?: number;
  setNumber: (newNumber: number) => void;
  setEnabled: (value: boolean) => void;
  /** Show a checkbox after the suffix that controls the enabled state of the input */
  showCheckbox?: boolean;
  /** Whether or not to show the number when the input is disabled */
  showNumberWhenDisabled?: boolean;
  /** The tooltip for the title */
  titleTooltip?: string;
  /** Maximum width of the number input, in monospace characters */
  maxWidthCharacters?: number;
};

type State = {
  focused: boolean;
  editing: boolean;
  editedValue: string;
};

class Input extends Component<Props, State> {
  inputElemRef: React.RefObject<HTMLInputElement>;
  constructor(props: Props) {
    super(props);
    this.state = {
      focused: false,
      editing: false,
      editedValue: ""
    };
    this.inputElemRef = React.createRef<HTMLInputElement>();
  }
  setEnabled = (event: React.ChangeEvent<HTMLInputElement>) => {
    this.props.setEnabled(event.target.checked);
  };

  unfocusedMode() {
    this.setState({
      focused: false,
      editing: false,
      editedValue: this.props.number.toString()
    });
  }

  focusedMode() {
    this.setState({
      focused: true,
      editing: false,
      editedValue: this.props.number.toString()
    });
    this.inputElemRef.current!.value = this.props.number.toString();
    this.inputElemRef.current!.select();
  }

  editingMode() {
    this.setState({
      focused: true,
      editing: true
    });
  }

  getDisplayStr(): string {
    if (this.state.editing) {
      return this.state.editedValue;
    } else {
      if (this.state.focused) {
        return this.props.number.toString();
      } else {
        return this.getRoundedStr();
      }
    }
  }

  getRoundedStr(): string {
    const precision = this.props.roundingPrecision ?? 3;
    return (
      Math.round(this.props.number * 10 ** precision) /
      10 ** precision
    ).toFixed(precision);
  }

  componentDidUpdate(
    prevProps: Readonly<Props>,
    prevState: Readonly<State>,
    snapshot?: any
  ): void {
    if (prevProps.number !== this.props.number) {
      // if the value has changed from the outside, make sure it is no longer
      // focused so concise precision is shown.
      this.unfocusedMode();
    }
  }

  render() {
    const showNumberWhenDisabled = this.props.showNumberWhenDisabled ?? true;
    let characters = this.getRoundedStr().length + 3;
    if (this.props.maxWidthCharacters !== undefined) {
      characters = Math.min(characters, this.props.maxWidthCharacters);
    }
    return (
      <>
        <Tooltip disableInteractive title={this.props.titleTooltip ?? ""}>
          <span
            className={
              styles.Title +
              " " +
              (this.props.enabled ? "" : styles.Disabled) +
              " " +
              (this.props.titleTooltip === undefined ? "" : styles.Tooltip)
            }
          >
            {this.props.title}
          </span>
        </Tooltip>
        <input
          ref={this.inputElemRef}
          type="text"
          className={
            styles.Number +
            (showNumberWhenDisabled ? " " + styles.ShowWhenDisabled : "")
          }
          style={{ minWidth: `${characters}ch` }}
          disabled={!this.props.enabled}
          // The below is needed to make inputs on CommandDraggables work
          onClick={(e) => e.stopPropagation()}
          onFocus={(e) => {
            this.focusedMode();
          }}
          onBlur={(e) => {
            const newNumber = parseFloat(
              parse(this.state.editedValue).evaluate().toString()
            );
            if (!Number.isNaN(newNumber)) {
              this.props.setNumber(newNumber);
            }
            this.unfocusedMode();
          }}
          onChange={(e) => {
            if (!this.state.editing) {
              this.editingMode();
            }
            this.setState({
              editedValue: e.target.value
            });
            e.preventDefault();
          }}
          onKeyDown={(e) => {
            if (e.key == "Enter") {
              this.inputElemRef.current?.blur();
              // let newNumber = parseFloat(this.state.editedValue);
              // if (!Number.isNaN(newNumber)) {
              //   this.props.setNumber(newNumber);
              // }
              // this.unfocusedMode();
            }
          }}
          value={this.getDisplayStr()}
          onMouseDown={(e) => {
            if (!this.state.focused) {
              this.focusedMode();
              e.preventDefault();
            }
          }}
          autoComplete="off"
          autoCorrect="off"
          autoCapitalize="off"
        ></input>
        <span
          className={
            styles.Suffix + " " + (this.props.enabled ? "" : styles.Disabled)
          }
        >
          {this.props.suffix}
        </span>
        {this.props.showCheckbox ? (
          <input
            type="checkbox"
            className={styles.Checkbox}
            checked={this.props.enabled}
            onChange={this.setEnabled}
          ></input>
        ) : (
          <span></span>
        )}
      </>
    );
  }
}
export default observer(Input);

// src-svelte/src/lib/components/input/Input.svelte
<script lang="ts">
  import styles from "./InputList.module.css"
  type  Props = {
  /** The text to show before the number */
  title: string;
  /** The text to show before the number */
  suffix: string;
  /** Whether the input should be editable, or else italic and grayed out */
  enabled: boolean;
  /** The value of the input */
  number: number;
  /** The number of decimal places to show when not editing. */
  roundingPrecision: number;
  setNumber: (newNumber: number) => void;
  setEnabled: (value: boolean) => void;
  /** Show a checkbox after the suffix that controls the enabled state of the input */
  showCheckbox: boolean;
  /** Whether or not to show the number when the input is disabled */
  showNumberWhenDisabled: boolean;
  /** The tooltip for the title */
  titleTooltip: string | undefined;
  /** Maximum width of the number input, in monospace characters */
  maxWidthCharacters: number;
  }
  let {
    title, suffix, enabled,
    number,roundingPrecision = 3,
    setNumber, setEnabled,
    showCheckbox = false,
    showNumberWhenDisabled = true,
    titleTooltip = undefined,
    maxWidthCharacters = 10
  } : Props = $props();
  let focused = $state(false);
  let editing = $state(false);
  let editedValue = $state("");
  let inputElemRef: HTMLInputElement;



  const handleSetEnabled = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEnabled(event.target.checked);
  };

  function unfocusedMode() {
      focused = false;
      editing= false;
      editedValue= number.toString();
  }

  function focusedMode() {
      focused =true,
      editing =false,
      editedValue =number.toString()
    inputElemRef.value = number.toString();
    inputElemRef.select();
  }

  function editingMode() {
      focused = true,
      editing = true
  }

  function getDisplayStr(): string {
    if (editing) {
      return editedValue;
    } else {
      if (focused) {
        return number.toString();
      } else {
        return getRoundedStr();
      }
    }
  }

  function getRoundedStr(): string {
    const precision = roundingPrecision ?? 3;
    return (
      Math.round(number * 10 ** precision) /
      10 ** precision
    ).toFixed(precision);
  }

  // componentDidUpdate(
  //   prevProps: Readonly<Props>,
  //   prevState: Readonly<State>,
  //   snapshot?: any
  // ): void {
  //   if (prevProps.number !== number) {
  //     // if the value has changed from the outside, make sure it is no longer
  //     // focused so concise precision is shown.
  //     unfocusedMode();
  //   }
  // }
    let characters = $derived(Math.min(getRoundedStr().length + 3, maxWidthCharacters ?? Infinity));
</script>
<div class="tooltip" data-tip={titleTooltip??""}>
          <span
            class={
              styles.Title +
              " " +
              (enabled ? "" : styles.Disabled) +
              " " +
              (titleTooltip === undefined ? "" : styles.Tooltip)
            }
          >
            {title}
          </span>
        </div>
        <input
        bind:this={inputElemRef}
          type="text"
          class={
            styles.Number +
            (showNumberWhenDisabled ? " " + styles.ShowWhenDisabled : "")
          }
          style={`min-width: ${characters}ch` }
          disabled={!enabled}
          
          onclick={(e) => e.stopPropagation()}
          onfocus={(e) => {
            focusedMode();
          }}
          onblur={(e) => {
            const newNumber = parseFloat(editedValue);
            if (!Number.isNaN(newNumber)) {
              setNumber(newNumber);
            }
            unfocusedMode();
          }}
          onchange={(e) => {
            if (!editing) {
              editingMode();
            }
            editedValue = e.target?.value ?? editedValue;
            e.preventDefault();
          }}
          onkeydown={(e) => {
            if (e.key == "Enter") {
              inputElemRef.blur();
              // let newNumber = parseFloat(state.editedValue);
              // if (!Number.isNaN(newNumber)) {
              //   setNumber(newNumber);
              // }
              // unfocusedMode();
            }
          }}
          value={getDisplayStr()}
          onmousedown={(e) => {
            if (!focused) {
              focusedMode();
              e.preventDefault();
            }
          }}
          autoComplete="off"
          autoCorrect="off"
          autoCapitalize="off"
        />
        <span
          class={
            styles.Suffix + " " + (enabled ? "" : styles.Disabled)
          }
        >
          {suffix}
        </span>
        {#if showCheckbox}
          <input
            type="checkbox"
            class={styles.Checkbox}
            checked={enabled}
            onchange={handleSetEnabled}
          />
          {:else}
          <span></span>
       {/if}
