// src/components/input/InputList.tsx
import { observer } from "mobx-react";
import React, { Component, PropsWithChildren } from "react";
import styles from "./InputList.module.css";

type Props = {
  noCheckbox?: boolean;
  rowGap?: number;
  style?: React.CSSProperties;
};

type State = object;

class InputList extends Component<PropsWithChildren<Props>, State> {
  state = {};
  render() {
    const className =
      styles.InputList +
      " " +
      ((this.props.noCheckbox ?? false) ? styles.NoCheckbox : "");
    const rowGap = this.props.rowGap ?? 0;
    return (
      <div className={className} style={{ rowGap, ...this.props.style }}>
        {this.props.children}
      </div>
    );
  }
}
export default observer(InputList);

// src-svelte/src/lib/components/input/InputList.svelte
<script lang="ts">

import styles from "./InputList.module.css";
let {
  rowGap = 0,
  noCheckbox = false,
  style
} : {rowGap: number, noCheckbox: boolean, style: string} = $props();



    const className =
      styles.InputList +
      " " +
      (noCheckbox ? styles.NoCheckbox : "");
    </script>
<div class={className} style={`rowgap: ${rowGap}; ${style}`}>
  <slot></slot>
</div>
