// src-svelte/src/lib/components/field/PathAnimationPanel.svelte
<script lang="ts">
    import { playbackTime } from "$lib/uistate.js";
    import { onDestroy } from "svelte";
    import {get} from "svelte/store"
    import {Trajectory} from "$lib/trajectory.js"
    import GraphLegend from "./GraphLegend.svelte";
    import PathAnimationSlider from "./PathAnimationSlider.svelte"
    import {GRAPH_PANEL_MIN_HEIGHT, graphPanelHeight, toggleGraphPanel} from "$lib/uistate"
    export let trajectory: Writable<TrajectorySample[]>

    let running = false;
    let timerId = 0;
    let totalTime =0;
    function updateTotalTime(traj) {
        
        if (traj.length < 2) {
            totalTime = 0;
        } else {
            totalTime = traj[traj.length-1].timestamp;
        }
    }
    $: updateTotalTime($trajectory);
    let i = 0;
    let then = Date.now();
    let step = (dt: number) => incrementTimer(dt);

    function onStart() {
    then = Date.now();
    running = true;
    if (
      Math.abs(
        totalTime - $playbackTime
      ) < 0.1
    ) {
      $playbackTime = 0;
    }
    window.cancelAnimationFrame(timerId);
    timerId = requestAnimationFrame(step);
  }
  function incrementTimer(_: number) {
    const dt = Date.now() - then;
    then = Date.now();
    if (running) {
      const pathAnimationTimestamp =
        $playbackTime;
      if (pathAnimationTimestamp > totalTime) {
        $playbackTime = 0;
      } else {
        playbackTime.update(time=>time+dt / 1e3)
      }

      timerId = requestAnimationFrame(step);
    }
  }

  function onStop() {
    running = false;
    if (timerId !== 0) {
      window.cancelAnimationFrame(timerId);
    }
  }
  onDestroy(onStop);

//   componentDidMount(): void {
//     hotkeys("space", "all", (e) => {
//       e.preventDefault();
//       if (this.state.running) {
//         this.onStop();
//       } else {
//         this.onStart();
//       }
//     });

//   }
</script>
<style>
    .Panel {
        color: white;
        gap: 1rem;
        width: 100%;
        max-height: var(--timeline-max-height);
        height: 1000;
        min-height: var(--timeline-min-height);
        resize:vertical;
        background-color: var(--background-dark-gray);
        box-sizing: border-box;
        display: block;
        border-top: thin solid var(--divider-gray);
    }
    .Content {
        display: flex;
        flex-direction: row;
        width: 100%;
        height: 100%;
    }
    .Content.hide {
        display: none;
    }
    .Sidebar {
        width: var(--sidebar-width);
        display: flex;
        flex-direction: column;
        height:100%;
        border-right: thin solid var(--divider-gray);
    }
    .PlayTime { 
        height:var(--timeline-min-height);
        border-bottom: thin solid var(--divider-gray);
        display:flex;
        flex-direction:row;
        justify-content: end;
    }

</style>
      <div
        class="Panel"
        style={`height:${$graphPanelHeight}px`}
      >
        <div
            class={
                "Content " + (totalTime == 0 ? "hide" : "")
            }
        >
        <div class="Sidebar">
            <div class="PlayTime">
                <div class="tooltip align-self-start" data-tip={"Plots"}>
                    <button class="btn btn-ghost btn-sm" on:click={
                        ()=>toggleGraphPanel()
                    }>
                    Plots
                        </button>
                    </div>
                <div class="tooltip align-self-end" data-tip={running ? "Pause":"Play"}>
                <button class="btn btn-ghost btn-sm" on:click={
                    ()=>running ? onStop() : onStart()
                }>
                {#if  running} Pause {:else} Play {/if}
                    </button>

                </div>
                <span
                class="w-min whitespace-nowrap"
                >{`${$playbackTime.toFixed(
                1
              )} s / ${totalTime.toFixed(1)} s`}</span>

            </div>
            <GraphLegend trajectory={$trajectory} time={$playbackTime}></GraphLegend>

        </div>
        <PathAnimationSlider trajectory={$trajectory} timeStore={playbackTime} totalTime={totalTime}></PathAnimationSlider>
        </div>
      </div>

// src/components/field/PathAnimationPanel.tsx
import { observer } from "mobx-react";
import { Component } from "react";
import { doc, uiState } from "../../document/DocumentManager";
import PathAnimationSlider from "./PathAnimationSlider";
import IconButton from "@mui/material/IconButton";
import PlayIcon from "@mui/icons-material/PlayArrow";
import PauseIcon from "@mui/icons-material/Pause";
import { autorun } from "mobx";
import { Tooltip } from "@mui/material";
import hotkeys from "hotkeys-js";

type Props = object;

type State = {
  running: boolean;
};

class PathAnimationPanel extends Component<Props, State> {
  state = {
    running: false
  };

  timerId = 0;
  totalTime = 0;
  i = 0;
  then = Date.now();
  step = (dt: number) => this.incrementTimer(dt);

  onStart() {
    this.then = Date.now();
    this.setState({ running: true });
    if (Math.abs(this.totalTime - uiState.pathAnimationTimestamp) < 0.1) {
      uiState.setPathAnimationTimestamp(0);
    }
    window.cancelAnimationFrame(this.timerId);
    this.timerId = requestAnimationFrame(this.step);
  }

  incrementTimer(_: number) {
    const dt = Date.now() - this.then;
    this.then = Date.now();
    if (this.state.running) {
      const pathAnimationTimestamp = uiState.pathAnimationTimestamp;
      if (pathAnimationTimestamp > this.totalTime) {
        uiState.setPathAnimationTimestamp(0);
      } else {
        uiState.setPathAnimationTimestamp(pathAnimationTimestamp + dt / 1e3);
      }

      this.timerId = requestAnimationFrame(this.step);
    }
  }

  onStop() {
    this.setState({ running: false });
    if (this.timerId !== 0) {
      window.cancelAnimationFrame(this.timerId);
    }
  }
  componentDidMount(): void {
    hotkeys("space", "all", (e) => {
      e.preventDefault();
      if (this.state.running) {
        this.onStop();
      } else {
        this.onStart();
      }
    });
    autorun(() => {
      const _ = doc.pathlist.activePathUUID;
      this.onStop();
    });
  }
  render() {
    const activePath = doc.pathlist.activePath;
    this.totalTime = doc.pathlist.activePath.traj.getTotalTimeSeconds();
    return (
      <div
        style={{
          color: "white",
          gap: "1rem",
          width: "100%",
          height: "2rem",
          backgroundColor: "var(--background-dark-gray)",
          paddingLeft: "10px",
          paddingRight: "10px",
          boxSizing: "border-box",
          display: "block",
          borderTop: "thin solid var(--divider-gray)"
        }}
      >
        <span
          style={{
            display: activePath.traj.fullTraj.length >= 2 ? "flex" : "none",
            flexDirection: "row",
            width: "100%",
            height: "100%",
            gap: "10px"
          }}
        >
          <Tooltip
            disableInteractive
            title={
              this.state.running
                ? "Pause Path Animation"
                : "Play Path Animation"
            }
          >
            <IconButton
              color="default"
              onClick={() => {
                if (this.state.running) {
                  this.onStop();
                } else {
                  this.onStart();
                }
              }}
            >
              {this.state.running ? (
                <PauseIcon></PauseIcon>
              ) : (
                <PlayIcon></PlayIcon>
              )}
            </IconButton>
          </Tooltip>
          <PathAnimationSlider></PathAnimationSlider>
        </span>
      </div>
    );
  }
}
export default observer(PathAnimationPanel);
