// src-svelte/src/lib/components/sidebar/Sidebar.svelte
<script lang="ts">
  import WaypointList from "./WaypointList.svelte"
  import PathSelector from "./PathSelector.svelte"
  import {Path} from "$lib/path.svelte.js";
  let {path}: {path:Path} = $props();
  let waypointSig = path.order;
  let constraints:any[] = [];
  let obstacles:any[] = [];
  let markers:any[] = [];
</script>
<style>
    .Container {
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    height: 100%;
    width: var(--sidebar-width);
    color: white;
    background-color: var(--background-dark-gray);
    border-right: thin solid var(--divider-gray);
    }
    .Container > :not(.divider, .Sidebar) {
    padding-left: 8px;
    }
    .Header { 
        flex-shrink: 0;
        height: var(--top-nav-height);
        border-bottom: thin solid var(--divider-gray);
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        padding-left: 0;
        z-index: 1000;
    }
    .SidebarHeading {
  display: grid;
  grid-template-columns: auto 33.6px;
  height: fit-content;
  align-items: center;
  min-height: 30px;
}
.Sidebar {
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: left;
  min-width: var(--sidebar-width);

  box-sizing: border-box;
  padding-block: 8px;
  overflow-x: auto;
  overflow-y: scroll;
  --grid-gap: 8px;
  --line-height: 32px;
  --icon-size: 24px;
}
.Sidebar>.divider:not(:empty) {
  padding-left: 8px;
}

.SidebarHr:not(:empty) {
  color: gray;
  font-size: 14px;
}

.WaypointList {
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  box-sizing: border-box;
}

.SidebarItem {
  color: white;
  border-left: 4px solid var(--background-light-gray);
  height: var(--line-height);
  /* background-color: var(--accent-purple); */
  /* border-radius: 50% !important; */
  width: 100%;
  font-size: 18px;
  flex-shrink: 0;
  margin-top: 0.25rem;
  margin-bottom: 0.25rem;
  margin-left: auto;
  margin-right: auto;
  padding-left: 8px;
  padding-top: auto;
  padding-bottom: auto;
  box-sizing: border-box;
  color: white;
  text-align: left;
  display: grid;
  grid-template-columns: var(--icon-size) 1fr max-content;
  align-items: center;
  gap: var(--grid-gap);
  padding-right: 8px;
  user-select: none;
  max-width: 100%;
}

.SidebarItem:hover:not(.Selected) {
  border-left: 4px solid var(--darker-purple);
}
.SidebarItem.Noninteractible {
  border-left: 4px solid transparent;
  background-color: transparent;
}
.Selected {
  border-width: 0;
  border-left: 4px solid var(--select-yellow);
}
.SidebarItem .SidebarIcon,
.SidebarItem .SidebarRightIcon {
  height: var(--icon-size);
  width: var(--icon-size);
}
.SidebarItem .SidebarVerticalLine {
  border-left: solid gray 1px;
  height: calc(100% + var(--grid-gap));
  transform: translate(calc(var(--icon-size) / 2), calc(var(--grid-gap) / -2));
}
.SidebarItem .SidebarLabel {
  color: white;
}
.SidebarItem .SidebarRightIcon {
  padding-right: 8px;
}

</style>
<div class="Container">
    <div
        class="Header"
    > 
      <span class="inline">
        <div class="tooltip tooltip-bottom" data-tip="Main Menu">
          <a href="/" class="btn btn-ghost btn-square btn-md">
            M
          </a>
        </div>
        
          <!-- <IconButton
            onClick={() => {
              toggleMainMenu();
            }}
          >
            <MenuIcon></MenuIcon>
          </IconButton> -->
        
        Choreo
      </span>
      <span class="inline">
        <div class="tooltip tooltip-bottom" data-tip="Undo">
          <button class="btn btn-ghost btn-square btn-md" class:btn-disabled={!path.history.canUndo} onclick={()=>path.history.undo()}>
            &lt;-
        <!-- <ArrowLeftOutline></ArrowLeftOutline> -->
      </button>
    </div>
        
    <div class="tooltip tooltip-bottom" data-tip="Redo">
      <button class="btn btn-ghost btn-square btn-md" class:btn-disabled={!path.history.canRedo} onclick={()=>path.history.redo()}>
        -&gt;
        <!-- <ArrowRightOutline></ArrowRightOutline> -->
      </button>
    </div>
      </span>
    </div>
    
    <div
      class="SidebarHeading"
      style="grid-template-columns: auto 33.6px 33.6px"
    >
      PATHS
      <span></span>
      <span></span>
      <!--<Tooltip title="Duplicate Path">
        <IconButton
          size="small"
          color="default"
          style={{
            float: "right"
          }}
          disabled={
            Object.keys(this.context.model.document.pathlist.paths)
              .length == 0
          }
          onClick={() =>
            this.context.model.document.pathlist.duplicatePath(
              this.context.model.document.pathlist.activePathUUID
            )
          }
        >
          <ContentCopy fontSize="small"></ContentCopy>
        </IconButton>
      </Tooltip>
      <Tooltip disableInteractive title="Add Path">
        <IconButton
          size="small"
          color="default"
          style={{
            float: "right"
          }}
          onClick={() => {
            this.context.model.document.pathlist.addPath("New Path", true);
            Promise.resolve().then(async () => {
              let id = await invoke("add_waypoint");
              await invoke("update_waypoint", {
                id,
                update:{
                x:2.0,
                isInitialGuess:false,
                control_interval_count: 20
              }})
              console.log(await invoke("get_waypoint", {id}))
            })
          }
          }
        >
          <Add fontSize="small"></Add>
        </IconButton>
      </Tooltip>-->
    </div>
    <div class="divider SidebarHr"></div>
    <div
      class="Sidebar max-h-300 min-h-50"
    >
      <PathSelector pathId={path.id}></PathSelector>
    </div>
    <div class="divider SidebarHr"></div>
    <div class="SidebarHeading">FEATURES</div>
    <div class="divider  SidebarHr"/>
    <div class="Sidebar">
      <div class="divider divider-start SidebarHr">WAYPOINTS</div>

      <WaypointList {path}></WaypointList>
      <div class="divider divider-start SidebarHr">CONSTRAINTS</div>
      <div class="WaypointList">
        {#each constraints as constraint}
        {/each}
        <!-- {this.context.model.document.pathlist.activePath.constraints.map(
          (constraint) => {
            return (
              <SidebarConstraint
                key={constraint.uuid}
                constraint={constraint}
              ></SidebarConstraint>
            );
          }
        )} -->
      </div>
      {#if constraints.length == 0}

        <div class={"SidebarItem Noninteractible"}>
          <span></span>
          <span style="color: gray; font-style: italic">
            No Constraints
          </span>
        </div>
      {/if}
      <div class="divider divider-start SidebarHr">OBSTACLES</div>
      {#if obstacles.length > 0 }
      
        <div class="WaypointList">
        {#each obstacles as obs}
            
        {/each}
        <!-- {this.context.model.document.pathlist.activePath.obstacles.map(
            (obstacle: ICircularObstacleStore, index: number) => {
            return (
                <SidebarObstacle
                obstacle={obstacle}
                index={index}
                context={this.context}
                ></SidebarObstacle>
            );
            }
        )} -->
        </div>
        {:else if obstacles.length == 0}
        <div
            class="SidebarItem Noninteractible"
        >
            <span></span>
            <span style="color: gray; font-style: italic">
            No Obstacles
            </span>
        </div>
    {/if}
    <div class="divider divider-start SidebarHr">MARKERS</div>
      <div class={"WaypointList"}>
        {#each  markers as marker}
            
        {/each}
        <!-- {this.context.model.document.pathlist.activePath.eventMarkers.map(
          (marker: IEventMarkerStore, index: number) => {
            return (
              <SidebarEventMarker
                marker={marker}
                index={index}
                context={this.context}
                key={marker.uuid}
              ></SidebarEventMarker>
            );
          }
        )} -->
      </div>
      {#if markers.length == 0}
      <div
        class="SidebarItem Noninteractible"
      >
        <span></span>
        <span style="color: gray; font-style: italic">
          No Markers
        </span>
      </div>
      {/if}
      <div class="divider"></div>
    </div>
    </div>

// src/components/sidebar/Sidebar.tsx
import React, { Component } from "react";
import { doc, uiState } from "../../document/DocumentManager";
import { observer } from "mobx-react";
import styles from "./Sidebar.module.css";
import { Divider, IconButton, Tooltip } from "@mui/material";
import WaypointList from "./WaypointList";
import PathSelector from "./PathSelector";
import MenuIcon from "@mui/icons-material/Menu";
import { ContentCopy, Redo, Undo } from "@mui/icons-material";
import Add from "@mui/icons-material/Add";
import SidebarConstraint from "./SidebarConstraint";
import SidebarObstacle from "./SidebarObstacle";
import { ICircularObstacleStore } from "../../document/CircularObstacleStore";
import SidebarEventMarker from "./SidebarEventMarker";
import { IEventMarkerStore } from "../../document/EventMarkerStore";

type Props = object;

type State = object;

class Sidebar extends Component<Props, State> {
  state = {};
  constructor(props: Props) {
    super(props);
  }

  render() {
    const { toggleMainMenu } = uiState;
    return (
      <div className={styles.Container}>
        <div
          style={{
            flexShrink: 0,
            height: "var(--top-nav-height)",
            borderBottom: "thin solid var(--divider-gray)",
            display: "flex",
            flexDirection: "row",
            justifyContent: "space-between",
            alignItems: "center",
            paddingLeft: 0,
            zIndex: 1000
          }}
        >
          <span>
            <Tooltip disableInteractive title="Main Menu">
              <IconButton
                onClick={() => {
                  toggleMainMenu();
                }}
              >
                <MenuIcon></MenuIcon>
              </IconButton>
            </Tooltip>
            Choreo
          </span>
          <span>
            <Tooltip disableInteractive title="Undo">
              <span>
                <IconButton
                  disabled={!doc.history.canUndo}
                  onClick={() => {
                    doc.undo();
                  }}
                >
                  <Undo></Undo>
                </IconButton>
              </span>
            </Tooltip>
            <Tooltip disableInteractive title="Redo">
              <span>
                <IconButton
                  disabled={!doc.history.canRedo}
                  onClick={() => {
                    doc.redo();
                  }}
                >
                  <Redo></Redo>
                </IconButton>
              </span>
            </Tooltip>
          </span>
        </div>
        <div
          className={styles.SidebarHeading}
          style={{ gridTemplateColumns: "auto 33.6px 33.6px" }}
        >
          PATHS
          <Tooltip disableInteractive title="Duplicate Path">
            <IconButton
              size="small"
              color="default"
              style={{
                float: "right"
              }}
              disabled={Object.keys(doc.pathlist.paths).length == 0}
              onClick={() =>
                doc.pathlist.duplicatePath(doc.pathlist.activePathUUID)
              }
            >
              <ContentCopy fontSize="small"></ContentCopy>
            </IconButton>
          </Tooltip>
          <Tooltip disableInteractive title="Add Path">
            <IconButton
              size="small"
              color="default"
              style={{
                float: "right"
              }}
              onClick={() => doc.pathlist.addPath("New Path", true)}
            >
              <Add fontSize="small"></Add>
            </IconButton>
          </Tooltip>
        </div>
        <Divider></Divider>
        <div
          className={styles.Sidebar}
          style={{ maxHeight: "300px", minHeight: "50px" }}
        >
          <PathSelector></PathSelector>
        </div>
        <Divider></Divider>
        <div className={styles.SidebarHeading}>FEATURES</div>
        <Divider flexItem></Divider>
        <div className={styles.Sidebar}>
          <Divider className={styles.SidebarDivider} textAlign="left" flexItem>
            <span>WAYPOINTS</span>
          </Divider>

          <WaypointList></WaypointList>
          <Divider className={styles.SidebarDivider} textAlign="left" flexItem>
            <span>CONSTRAINTS</span>
          </Divider>
          <div className={styles.WaypointList}>
            {doc.pathlist.activePath.path.constraints.map((constraint) => {
              return (
                <SidebarConstraint
                  key={constraint.uuid}
                  constraint={constraint}
                ></SidebarConstraint>
              );
            })}
          </div>
          {doc.pathlist.activePath.path.constraints.length == 0 && (
            <div className={styles.SidebarItem + " " + styles.Noninteractible}>
              <span></span>
              <span style={{ color: "gray", fontStyle: "italic" }}>
                No Constraints
              </span>
            </div>
          )}
          {(doc.usesObstacles ||
            doc.pathlist.activePath.path.obstacles.includes(
              doc.selectedSidebarItem
            )) && (
            <>
              <Divider
                className={styles.SidebarDivider}
                textAlign="left"
                flexItem
              >
                <span>OBSTACLES</span>
              </Divider>
              <div className={styles.WaypointList}>
                {doc.pathlist.activePath.path.obstacles.map(
                  (obstacle: ICircularObstacleStore, index: number) => {
                    return (
                      <SidebarObstacle
                        obstacle={obstacle}
                        index={index}
                      ></SidebarObstacle>
                    );
                  }
                )}
              </div>
              {doc.pathlist.activePath.path.obstacles.length == 0 && (
                <div
                  className={styles.SidebarItem + " " + styles.Noninteractible}
                >
                  <span></span>
                  <span style={{ color: "gray", fontStyle: "italic" }}>
                    No Obstacles
                  </span>
                </div>
              )}
            </>
          )}
          <Divider className={styles.SidebarDivider} textAlign="left" flexItem>
            <span>MARKERS</span>
          </Divider>
          <div className={styles.WaypointList}>
            {doc.pathlist.activePath.traj.markers.map(
              (marker: IEventMarkerStore, index: number) => {
                return (
                  <SidebarEventMarker
                    marker={marker}
                    index={index}
                    key={marker.uuid}
                  ></SidebarEventMarker>
                );
              }
            )}
          </div>
          {doc.pathlist.activePath.traj.markers.length == 0 && (
            <div className={styles.SidebarItem + " " + styles.Noninteractible}>
              <span></span>
              <span style={{ color: "gray", fontStyle: "italic" }}>
                No Event Markers
              </span>
            </div>
          )}
          <Divider></Divider>
        </div>
      </div>
    );
  }
}
export default observer(Sidebar);
